steps:

- name: 'binxio/terratest-runner-gcp'
  args: ['go', 'mod', 'init', 'terraunittest']
  dir: 'tests/unit/${_MOD_NAME}'

- name: 'binxio/terratest-runner-gcp'
  args: ['go', 'mod', 'tidy']
  dir: 'tests/unit/${_MOD_NAME}'

- name: 'binxio/terratest-runner-gcp'
  args: ['go', 'test', '-v', '.', '-timeout', '120m', '-p', '1']
  dir: 'tests/unit/${_MOD_NAME}'
  env: ['GCLOUD_PROJECT=automated-post-deploy-hook']

timeout: 1200s