steps:

- name: 'binxio/terratest-runner-gcp'
  entrypoint: 'ash'
  args:
  - '-c'
  - '-eEuo'
  - 'pipefail'
  - |
    go mod init terraunittest \
    && go mod tidy \
    && go test -v -timeout 30m
  dir: 'tests/integration'
  env: ['GCLOUD_PROJECT=automated-post-deploy-hook']

timeout: 1800s